version: '3.8'

services:
  up-skillium-server:
    container_name: up-skillium-server
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5010:5010"
    restart: always
    env_file:
      - .env
  
