import { IReview } from "@/types/review.type";

export const reviewsData: IReview[] = [
  {
    id: "r1",
    feedback:
      "This course completely changed the way I approach web development!",
    reviewToModel: "Course",
    rating: 5,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
    reviewer: {
      id: "u1",
      name: "Anika Rahman",
      image: "./success-students/programmer-female-15.png",
    },
    reviewTo: {
      id: "c1",
      title: "Full-Stack JavaScript Developer",
      image: "./assets/courseImages/full-stack.png",
    },
  },
  {
    id: "r2",
    feedback: "The instructor was very clear and gave great examples.",
    reviewToModel: "Instructor",
    rating: 4,
    createdAt: new Date("2025-05-20"),
    updatedAt: new Date("2025-05-20"),
    reviewer: {
      id: "u2",
      name: "Tariq Islam",
      image: "./success-students/programmer-male-3.png",
    },
    reviewTo: {
      id: "i1",
      name: "Sarah Hossain",
      image: "./success-students/programmer-male-12.png",
    },
  },
  {
    id: "r3",
    feedback: "Excellent design course. I learned so much about Figma!",
    reviewToModel: "Course",
    rating: 5,
    createdAt: new Date("2025-04-15"),
    updatedAt: new Date("2025-04-15"),
    reviewer: {
      id: "u3",
      name: "Mahir Khan",
      image: "./success-students/programmer-male-6.png",
    },
    reviewTo: {
      id: "c2",
      title: "UI/UX Design Essentials",
      image: "./assets/courseImages/ui-ux-design.png",
    },
  },
  {
    id: "r4",
    feedback: "Very knowledgeable and friendly instructor!",
    reviewToModel: "Instructor",
    rating: 5,
    createdAt: new Date("2025-03-29"),
    updatedAt: new Date("2025-03-29"),
    reviewer: {
      id: "u4",
      name: "Farhana Jahan",
      image: "./success-students/programmer-female-13.png",
    },
    reviewTo: {
      id: "i2",
      name: "Asif Mahmud",
      image: "./success-students/programmer-male-1.png",
    },
  },
  {
    id: "r5",
    feedback: "Good content but could improve the delivery style.",
    reviewToModel: "Course",
    rating: 3,
    createdAt: new Date("2025-06-05"),
    updatedAt: new Date("2025-06-05"),
    reviewer: {
      id: "u5",
      name: "Lamia Khatun",
      image: "./success-students/programmer-female-16.png",
    },
    reviewTo: {
      id: "c3",
      title: "SEO Fundamentals",
      image: "./assets/courseImages/seo.png",
    },
  },
  {
    id: "r6",
    feedback: "Loved the real-world projects. Highly recommend!",
    reviewToModel: "Course",
    rating: 5,
    createdAt: new Date("2025-06-10"),
    updatedAt: new Date("2025-06-10"),
    reviewer: {
      id: "u6",
      name: "Nabil Chowdhury",
      image: "./success-students/programmer-male-10.png",
    },
    reviewTo: {
      id: "c4",
      title: "Web Design Mastery",
      image: "./assets/courseImages/web-development-course.png",
    },
  },
  {
    id: "r7",
    feedback: "The instructor explains backend concepts so clearly.",
    reviewToModel: "Instructor",
    rating: 4,
    createdAt: new Date("2025-05-02"),
    updatedAt: new Date("2025-05-02"),
    reviewer: {
      id: "u7",
      name: "Raihan Uddin",
      image: "./success-students/programmer-male-5.png",
    },
    reviewTo: {
      id: "i3",
      name: "Nusrat Alam",
      image: "./success-students/programmer-female-4.png",
    },
  },
  {
    id: "r8",
    feedback: "Very detailed and hands-on course. Perfect for beginners!",
    reviewToModel: "Course",
    rating: 5,
    createdAt: new Date("2025-06-15"),
    updatedAt: new Date("2025-06-15"),
    reviewer: {
      id: "u8",
      name: "Sadia Karim",
      image: "./success-students/programmer-female-15.png",
    },
    reviewTo: {
      id: "c5",
      title: "Graphic Design for Beginners",
      image: "./assets/courseImages/graphic-design.png",
    },
  },
  {
    id: "r9",
    feedback: "Great instructor with lots of patience and clarity.",
    reviewToModel: "Instructor",
    rating: 5,
    createdAt: new Date("2025-04-25"),
    updatedAt: new Date("2025-04-25"),
    reviewer: {
      id: "u9",
      name: "Tanvir Rahman",
      image: "./success-students/programmer-male-12.png",
    },
    reviewTo: {
      id: "i4",
      name: "Dr. Zarin Akter",
      image: "./success-students/programmer-female-14.png",
    },
  },
  {
    id: "r10",
    feedback: "Concise and powerful lessons with real coding tasks.",
    reviewToModel: "Course",
    rating: 4,
    createdAt: new Date("2025-06-20"),
    updatedAt: new Date("2025-06-20"),
    reviewer: {
      id: "u10",
      name: "Abir Hossain",
      image: "./success-students/programmer-male-11.png",
    },
    reviewTo: {
      id: "c6",
      title: "Python for Beginners",
      image: "./assets/courseImages/python.png",
    },
  },
];
