import { v4 as uuidv4 } from "uuid";

const successStudentsData = [
  {
    id: uuidv4(),
    name: "John Doe",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    course: "Web Development",
    score: 95,
  },
  {
    id: uuidv4(),
    name: "Jane Smith",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    course: "Graphic Design",
    score: 66,
  },
  {
    id: uuidv4(),
    name: "Alice Johnson",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    course: "Digital Marketing",
    score: 40,
  },
  {
    id: uuidv4(),
    name: "Michael Brown",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    course: "Data Science",
    score: 65,
  },
  {
    id: uuidv4(),
    name: "Emily Davis",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
    course: "UI/UX Design",
    score: 71,
  },
  {
    id: uuidv4(),
    name: "Chris Wilson",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    course: "Cybersecurity",
    score: 88,
  },
  {
    id: uuidv4(),
    name: "Sophia Miller",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    course: "Project Management",
    score: 54,
  },
  {
    id: uuidv4(),
    name: "James Moore",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
    course: "Machine Learning",
    score: 57,
  },
  {
    id: uuidv4(),
    name: "Olivia Taylor",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
    course: "Business Analytics",
    score: 51,
  },
  {
    id: uuidv4(),
    name: "Daniel Anderson",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
    course: "Cloud Computing",
    score: 77,
  },
  {
    id: uuidv4(),
    name: "Mia White",
    image: "https://randomuser.me/api/portraits/women/11.jpg",
    course: "Photography",
    score: 60,
  },
  {
    id: uuidv4(),
    name: "Benjamin Harris",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    course: "Video Editing",
    score: 90,
  },
  {
    id: uuidv4(),
    name: "Charlotte Clark",
    image: "https://randomuser.me/api/portraits/women/13.jpg",
    course: "App Development",
    score: 61,
  },
  {
    id: uuidv4(),
    name: "Liam Rodriguez",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
    course: "Game Design",
    score: 53,
  },
  {
    id: uuidv4(),
    name: "Amelia Lewis",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
    course: "Artificial Intelligence",
    score: 78,
  },
  {
    id: uuidv4(),
    name: "Ethan Walker",
    image: "https://randomuser.me/api/portraits/men/16.jpg",
    course: "Robotics",
    score: 99,
  },
  {
    id: uuidv4(),
    name: "Harper Hall",
    image: "https://randomuser.me/api/portraits/women/17.jpg",
    course: "Digital Illustration",
    score: 40,
  },
  {
    id: uuidv4(),
    name: "Lucas Allen",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
    course: "SEO Optimization",
    score: 33,
  },
  {
    id: uuidv4(),
    name: "Ella Young",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
    course: "Content Writing",
    score: 28,
  },
  {
    id: uuidv4(),
    name: "Alexander King",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    course: "Blockchain Technology",
    score: 25,
  },
  {
    id: uuidv4(),
    name: "Grace Carter",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
    course: "Digital Illustration",
    score: 91,
  },
  {
    id: uuidv4(),
    name: "Henry Martin",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    course: "Cloud Computing",
    score: 74,
  },
  {
    id: uuidv4(),
    name: "Isabella Wright",
    image: "https://randomuser.me/api/portraits/women/23.jpg",
    course: "Web Development",
    score: 88,
  },
  {
    id: uuidv4(),
    name: "Jack Thompson",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    course: "UI/UX Design",
    score: 64,
  },
  {
    id: uuidv4(),
    name: "Scarlett Adams",
    image: "https://randomuser.me/api/portraits/women/25.jpg",
    course: "Machine Learning",
    score: 79,
  },
  {
    id: uuidv4(),
    name: "Liam Harris",
    image: "https://randomuser.me/api/portraits/men/26.jpg",
    course: "Photography",
    score: 58,
  },
  {
    id: uuidv4(),
    name: "Chloe Brown",
    image: "https://randomuser.me/api/portraits/women/27.jpg",
    course: "Graphic Design",
    score: 82,
  },
  {
    id: uuidv4(),
    name: "Mason Wilson",
    image: "https://randomuser.me/api/portraits/men/28.jpg",
    course: "Artificial Intelligence",
    score: 92,
  },
  {
    id: uuidv4(),
    name: "Victoria Garcia",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    course: "Digital Marketing",
    score: 85,
  },
  {
    id: uuidv4(),
    name: "Samuel White",
    image: "https://randomuser.me/api/portraits/men/30.jpg",
    course: "Business Analytics",
    score: 55,
  },
  {
    id: uuidv4(),
    name: "Ella Jones",
    image: "https://randomuser.me/api/portraits/women/31.jpg",
    course: "Project Management",
    score: 63,
  },
  {
    id: uuidv4(),
    name: "Ryan Taylor",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    course: "Cybersecurity",
    score: 96,
  },
  {
    id: uuidv4(),
    name: "Lily Moore",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    course: "App Development",
    score: 72,
  },
  {
    id: uuidv4(),
    name: "David Anderson",
    image: "https://randomuser.me/api/portraits/men/34.jpg",
    score: 72,
  },
  {
    id: uuidv4(),
    name: "Md Rubel Ahmed Rana",
    image: "https://randomuser.me/api/portraits/men/35.jpg",
    score: 52,
  },
  {
    id: uuidv4(),
    name: "Bodrul Amin",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
    score: 80,
  },
  {
    id: uuidv4(),
    name: "Tamanna",
    image: "https://randomuser.me/api/portraits/women/37.jpg",
    score: 90,
  },
  {
    id: uuidv4(),
    name: "Rumina",
    image: "https://randomuser.me/api/portraits/women/38.jpg",
    score: 40,
  },
  {
    id: uuidv4(),
    name: "Nusrat Erfan Ruhi",
    image: "https://randomuser.me/api/portraits/women/39.jpg",
    score: 60,
  },
  {
    id: uuidv4(),
    name: "Ahad Ahsan",
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    score: 80,
  },
  {
    id: uuidv4(),
    name: "Tahmida",
    image: "https://randomuser.me/api/portraits/women/41.jpg",
    score: 99,
  },
  {
    id: uuidv4(),
    name: "Rubel",
    image: "https://randomuser.me/api/portraits/men/42.jpg",
    score: 98,
  },
  {
    id: uuidv4(),
    name: "Sumaiya Kabir",
    image: "https://randomuser.me/api/portraits/women/43.jpg",
    score: 80,
  },
  {
    id: uuidv4(),
    name: "Saleh Ahmed",
    image: "https://randomuser.me/api/portraits/men/44.jpg",
    score: 70,
  },
  {
    id: uuidv4(),
    name: "Kamran Ahmed Sojib",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    score: 60,
  },
];
export default successStudentsData;
